#!/usr/bin/env ruby
# frozen_string_literal: true

require "digest"

profile_name, path = ARGV
unless profile_name == "broad" && path && ARGV.length == 2
  abort "Usage: validate_shadowrocket_ruleset.rb broad RULESET"
end

content = File.binread(path)
lines = content.lines(chomp: true)
errors = []

errors << "Ruleset must end with a newline" unless content.end_with?("\n")

def one_metadata_line(lines, prefix, errors)
  matches = lines.select { |line| line.start_with?(prefix) }
  errors << "Expected exactly one #{prefix} metadata line" unless matches.length == 1
  matches.first
end

generator = one_metadata_line(lines, "# Generated by ", errors)
errors << "Unexpected generator metadata" unless generator == "# Generated by tools/build_shadowrocket_cn_rules.rb; do not edit by hand."

profile = one_metadata_line(lines, "# Profile: ", errors)
errors << "Ruleset profile must be broad" unless profile == "# Profile: broad"

source = one_metadata_line(lines, "# Source: ", errors)
source_pattern = %r{\A# Source: https://raw\.githubusercontent\.com/MetaCubeX/meta-rules-dat/[0-9a-f]{40}/geo/geosite/cn\.list\z}
errors << "Source must be a fixed MetaCubeX commit URL" unless source&.match?(source_pattern)

source_sha = one_metadata_line(lines, "# Source SHA-256: ", errors)
errors << "Source SHA-256 metadata is invalid" unless source_sha&.match?(/\A# Source SHA-256: [0-9a-f]{64}\z/)

source_list = one_metadata_line(lines, "# Source list: ", errors)
errors << "Source list must be geosite-cn" unless source_list == "# Source list: geosite-cn"

upstream_license = one_metadata_line(lines, "# Upstream license: ", errors)
expected_license = "# Upstream license: GPL-3.0; https://github.com/MetaCubeX/meta-rules-dat/blob/master/LICENSE"
errors << "MetaCubeX GPL-3.0 notice is missing or incorrect" unless upstream_license == expected_license

generated_at = one_metadata_line(lines, "# Generated at: ", errors)
errors << "Generated timestamp is invalid" unless generated_at&.match?(/\A# Generated at: \d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z\z/)

converted = one_metadata_line(lines, "# Converted rules: ", errors)
converted_match = converted&.match(/\A# Converted rules: (\d+); skipped non-domain rules: (\d+)\z/)
converted_count = converted_match&.captures&.first&.to_i
skipped_count = converted_match&.captures&.last&.to_i
errors << "Converted-rule metadata is invalid" unless converted_match
errors << "Broad conversion must not skip source rules" unless skipped_count.nil? || skipped_count.zero?

rules = lines.reject { |line| line.empty? || line.start_with?("#") }
invalid_rule = rules.find do |rule|
  !rule.match?(/\ADOMAIN-SUFFIX,[^,\s]+\z/)
end
errors << "Invalid Shadowrocket broad rule: #{invalid_rule}" if invalid_rule
errors << "Ruleset contains duplicate rules" unless rules.uniq.length == rules.length
errors << "Rule count does not match metadata" if converted_count && converted_count != rules.length
unless (100_000..200_000).cover?(rules.length)
  errors << "Broad rule count is outside the 100000..200000 safety range: #{rules.length}"
end

%w[DOMAIN-SUFFIX,cn DOMAIN-SUFFIX,taobao.com DOMAIN-SUFFIX,bilibili.com].each do |representative|
  errors << "Missing representative rule: #{representative}" unless rules.include?(representative)
end

if errors.empty?
  puts "OK [broad]: #{rules.length} policy-free Shadowrocket rules; file SHA-256 #{Digest::SHA256.hexdigest(content)}."
else
  errors.each { |error| warn "Error: #{error}" }
  exit 1
end
